export const ALL_TASK_REQUEST="ALL_TASK_REQUEST";
export const ALL_TASK_SUCCESS="ALL_TASK_SUCCESS";
export const ALL_TASK_FAIL="ALL_TASK_FAIL";

export const NEW_TASK_REQUEST="NEW_TASK_REQUEST";
export const NEW_TASK_SUCCESS="NEW_TASK_SUCCESS";
export const NEW_TASK_FAIL="NEW_TASK_FAIL";
export const NEW_TASK_RESET="NEW_TASK_RESET";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_RESET = "UPDATE_TASK_RESET";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_RESET = "DELETE_TASK_RESET";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const CLEAR_ERROR="CLEAR_ERROR";